/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrderImport } from './routes/Order'

// Create/Update Routes

const OrderRoute = OrderImport.update({
  path: '/Order',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Order': {
      id: '/Order'
      path: '/Order'
      fullPath: '/Order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Order': typeof OrderRoute
}

export interface FileRoutesByTo {
  '/Order': typeof OrderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Order': typeof OrderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Order'
  fileRoutesByTo: FileRoutesByTo
  to: '/Order'
  id: '__root__' | '/Order'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OrderRoute: typeof OrderRoute
}

const rootRouteChildren: RootRouteChildren = {
  OrderRoute: OrderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/Order"
      ]
    },
    "/Order": {
      "filePath": "Order.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
